export const TOP_BAR_BASE_HEIGHT = 44;
export const TOP_BAR_PILLS_HEIGHT = 48;
export const TOP_BAR_COLLAPSED_PADDING = 4;
export const TOP_BAR_EXPANDED_PADDING = 8;

export const TOP_BAR_COLLAPSED_CONTENT_HEIGHT = TOP_BAR_BASE_HEIGHT + TOP_BAR_COLLAPSED_PADDING;
export const TOP_BAR_EXPANDED_CONTENT_HEIGHT = TOP_BAR_BASE_HEIGHT + TOP_BAR_PILLS_HEIGHT + TOP_BAR_EXPANDED_PADDING;
export const TOP_BAR_PILLS_AREA_HEIGHT = TOP_BAR_EXPANDED_CONTENT_HEIGHT - TOP_BAR_COLLAPSED_CONTENT_HEIGHT;
